name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_call:  # Allow being called by other workflows

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv sync --extra dev
        cd food-data-central-mcp-server
        npm install && npm run build
        cd ..
    
    - name: Run linting
      run: |
        uv run python -m ruff check .
      env:
        PYTHONPATH: ${{ github.workspace }}/src
    
    - name: Run tests
      run: |
        uv run pytest tests/ -m unit -v
      env:
        PYTHONPATH: ${{ github.workspace }}/src